apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: k8s-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-app-container
        image: aggrag/server-repo:latest
        ports:
        - containerPort: 4000
        env:
          - name: NAME
            value: "Raghav Aggarwal"
