apiVersion: v1
kind: Service
metadata:
  name: server-app-service
  namespace: k8s-challenge
spec:
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 4000 
  type: LoadBalancer
